// import * as o01 from './01.primitive-data-types';
// import * as o02 from './02.strings';
// import * as o03 from './03.arraysOne';
// import * as o03 from "./03.arraysTwo";
// import * as o04 from './04.objectsOne';
// import * as o04 from './04.objectsTwo';
// import * as o05 from './05.date';
// import * as o06 from './06.functionsOne';
// import * as o06 from './06.functionsTwo';
// import * as o07 from "./07.promisesOne";
// import * as o07 from "./07.promisesTwo";
import * as o07 from "./07.promisesWith-AsyncFunc";
// import * as o08 from './08.async-functions';
// import * as o09 from './09.iterators';
// import * as o10 from './10.sync-generators';
// import * as o11 from './11.dom';
