// import * as o01 from './01.primitive-data-types';
// import * as o02 from './02.strings';
// import * as o03 from './03.numbers';
// import * as o04 from './04.arraysOne';
// import * as o05 from './05.arraysTwo';
import * as o06 from './06.objectsOne';
// import * as o07 from './07.objectsTwo';
// import * as o08 from './08.date';
// import * as o09 from './09.functionsOne';
// import * as o10 from './10.functionsTwo';
// import * as o11 from './11.functionsThree';
// import * as o12 from './12.class';
// import * as o13 from './13.promises';
// import * as o14 from './14.async-functions';
// import * as o15 from './15.iterators';
// import * as o16 from './16.sync-generators';
// import * as o17 from './17.dom';
